# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: utPLSQL
google_analytics: UA-80445365-1
email:
description: > # this means to ignore newlines until "baseurl:"
  utPLSQL <br/>
  Unit Testing Framework for Oracle PL/SQL.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://utPLSQL.github.com" # the base hostname & protocol for your site
twitter_username: utplsql
github_username:  utplsql
# Build settings
markdown: kramdown
exclude: ["readme.md","dl-files"]
